package com.lwkslick.hitboxreveal.client;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;
import net.minecraft.client.MinecraftClient;
import java.awt.Color;

public class ConfigScreen {

    public static Screen create(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
                .title(Text.literal("HitboxReveal"))
                .save(ModConfig::save)

                // ── General ──────────────────────────────────────────────────────
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("General"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("General"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Master toggle for HitboxReveal.")))
                                        .binding(true, () -> ModConfig.enabled, v -> ModConfig.enabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Permanent"))
                                        .description(OptionDescription.of(Text.literal("Show hitboxes permanently instead of fading after duration.")))
                                        .binding(false, () -> ModConfig.permanent, v -> ModConfig.permanent = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Duration"))
                                        .description(OptionDescription.of(Text.literal("How long the hitbox stays visible after a hit (in ticks). 20 ticks = 1 second.")))
                                        .binding(60, () -> ModConfig.revealTicks, v -> ModConfig.revealTicks = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(20, 2400).step(20))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Outline"))
                                        .description(OptionDescription.of(Text.literal("Render the hitbox outline.")))
                                        .binding(true, () -> ModConfig.outline, v -> ModConfig.outline = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Hitbox Size"))
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Box size preset"))
                                        .description(OptionDescription.of(Text.literal("Override rendered player hitbox size. Useful on servers with custom entity scaling.")))
                                        .binding(0, () -> ModConfig.playerSizePreset, v -> ModConfig.playerSizePreset = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 2).step(1)
                                                .valueFormatter(i -> Text.literal(i == 0 ? "Default" : i == 1 ? "Minimum" : "Maximum")))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Min preset scale"))
                                        .description(OptionDescription.of(Text.literal("Scale applied when preset is Minimum.")))
                                        .binding(0.6f, () -> ModConfig.playerSizeMin, v -> ModConfig.playerSizeMin = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 1.0f).step(0.05f).valueFormatter(f -> Text.literal(String.format("%.2fx", f))))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Max preset scale"))
                                        .description(OptionDescription.of(Text.literal("Scale applied when preset is Maximum.")))
                                        .binding(1.5f, () -> ModConfig.playerSizeMax, v -> ModConfig.playerSizeMax = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(1.0f, 3.0f).step(0.1f).valueFormatter(f -> Text.literal(String.format("%.2fx", f))))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Appearance"))
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Line width"))
                                        .description(OptionDescription.of(Text.literal("Thickness of the hitbox outline.")))
                                        .binding(2.0f, () -> ModConfig.lineWidth, v -> ModConfig.lineWidth = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(2.0f, 8.0f).step(0.5f))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Fill opacity"))
                                        .description(OptionDescription.of(Text.literal("Opacity of the hitbox fill. 0 = invisible, 1 = fully opaque.")))
                                        .binding(0.25f, () -> ModConfig.fillOpacity, v -> ModConfig.fillOpacity = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.0f, 1.0f).step(0.05f).valueFormatter(f -> Text.literal(String.format("%.0f%%", f * 100))))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Eye height box"))
                                        .description(OptionDescription.of(Text.literal("Render a separate box at the target's eye height.")))
                                        .binding(false, () -> ModConfig.eyeHeightBox, v -> ModConfig.eyeHeightBox = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Look vector"))
                                        .description(OptionDescription.of(Text.literal("Render a line showing where the target is looking.")))
                                        .binding(false, () -> ModConfig.lookVector, v -> ModConfig.lookVector = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Look vector length"))
                                        .description(OptionDescription.of(Text.literal("Length of the look vector line in blocks.")))
                                        .binding(2.0f, () -> ModConfig.lookVectorLength, v -> ModConfig.lookVectorLength = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 10.0f).step(0.5f))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Look vector width"))
                                        .description(OptionDescription.of(Text.literal("Thickness of the look vector line.")))
                                        .binding(2.0f, () -> ModConfig.lookVectorWidth, v -> ModConfig.lookVectorWidth = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(2.0f, 8.0f).step(0.5f))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Range"))
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Close range threshold"))
                                        .description(OptionDescription.of(Text.literal("Distance in blocks at which the close-range color activates.")))
                                        .binding(3.0f, () -> ModConfig.closeRangeThreshold, v -> ModConfig.closeRangeThreshold = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(1.0f, 8.0f).step(0.1f).valueFormatter(f -> Text.literal(String.format("%.1f blocks", f))))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Auto-Reveal"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Automatically reveal nearby enemy player hitboxes without needing to hit them. Deactivates if more than the max number of enemies are in range.")))
                                        .binding(false, () -> ModConfig.soloAutoReveal, v -> ModConfig.soloAutoReveal = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Max players"))
                                        .description(OptionDescription.of(Text.literal("Maximum number of nearby players to auto-reveal at once. 1 = classic solo mode.")))
                                        .binding(1, () -> ModConfig.soloAutoMaxPlayers, v -> ModConfig.soloAutoMaxPlayers = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 5).step(1))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Detection range"))
                                        .description(OptionDescription.of(Text.literal("Radius in blocks to scan for nearby players.")))
                                        .binding(20.0f, () -> ModConfig.soloAutoRange, v -> ModConfig.soloAutoRange = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(5.0f, 300.0f).step(5.0f).valueFormatter(f -> Text.literal(String.format("%.0f blocks", f))))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Linger ticks"))
                                        .description(OptionDescription.of(Text.literal("How many ticks the hitbox stays on after the auto-reveal condition is lost. 20 = 1 second.")))
                                        .binding(40, () -> ModConfig.soloAutoLinger, v -> ModConfig.soloAutoLinger = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 200).step(10))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Action bar messages"))
                                        .description(OptionDescription.of(Text.literal("Show 'Auto-Reveal: ON/LOST' in the action bar when auto-reveal activates or deactivates.")))
                                        .binding(true, () -> ModConfig.soloAutoActionBar, v -> ModConfig.soloAutoActionBar = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Pulse range indicator"))
                                        .description(OptionDescription.of(Text.literal("Pulse the range indicator circle while auto-reveal is active. Requires Range Indicator to be enabled in Visuals.")))
                                        .binding(true, () -> ModConfig.soloAutoRangeIndicatorPulse, v -> ModConfig.soloAutoRangeIndicatorPulse = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .build())

                // ── Visuals ──────────────────────────────────────────────────────
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Visuals"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Colors"))
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Default color"))
                                        .description(OptionDescription.of(Text.literal("Hitbox color when target is marked normally.")))
                                        .binding(new Color(ModConfig.colorDefault, true), () -> new Color(ModConfig.colorDefault, true), v -> ModConfig.colorDefault = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Close range color"))
                                        .description(OptionDescription.of(Text.literal("Hitbox color when target is within close range threshold.")))
                                        .binding(new Color(ModConfig.colorClose, true), () -> new Color(ModConfig.colorClose, true), v -> ModConfig.colorClose = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Crit color"))
                                        .description(OptionDescription.of(Text.literal("Hitbox color when target is airborne with full attack cooldown (crit-ready).")))
                                        .binding(new Color(ModConfig.colorCrit, true), () -> new Color(ModConfig.colorCrit, true), v -> ModConfig.colorCrit = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Gradient"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Gradient enabled"))
                                        .description(OptionDescription.of(Text.literal("Toggle the gradient fill on hitboxes.")))
                                        .binding(true, () -> ModConfig.gradientEnabled, v -> ModConfig.gradientEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Flip gradient direction"))
                                        .description(OptionDescription.of(Text.literal("When ON, gradient goes bottom to top instead of top to bottom.")))
                                        .binding(false, () -> ModConfig.gradientFlip, v -> ModConfig.gradientFlip = v)
                                        .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Gradient top color"))
                                        .description(OptionDescription.of(Text.literal("Top color of the hitbox gradient. Used for all states unless per-state gradients is on.")))
                                        .binding(new Color(ModConfig.colorGradientTop, true), () -> new Color(ModConfig.colorGradientTop, true), v -> ModConfig.colorGradientTop = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Per-state gradients"))
                                        .description(OptionDescription.of(Text.literal("Use different gradient top colors for each hitbox state (default, close range, crit).")))
                                        .binding(false, () -> ModConfig.perStateGradient, v -> ModConfig.perStateGradient = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Gradient top (default)"))
                                        .description(OptionDescription.of(Text.literal("Top gradient color for the default state. Only used when per-state gradients is on.")))
                                        .binding(new Color(ModConfig.colorGradientTop, true), () -> new Color(ModConfig.colorGradientTop, true), v -> ModConfig.colorGradientTop = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Gradient top (close range)"))
                                        .description(OptionDescription.of(Text.literal("Top gradient color for the close range state. Only used when per-state gradients is on.")))
                                        .binding(new Color(ModConfig.colorGradientTopClose, true), () -> new Color(ModConfig.colorGradientTopClose, true), v -> ModConfig.colorGradientTopClose = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Gradient top (crit)"))
                                        .description(OptionDescription.of(Text.literal("Top gradient color for the crit state. Only used when per-state gradients is on.")))
                                        .binding(new Color(ModConfig.colorGradientTopCrit, true), () -> new Color(ModConfig.colorGradientTopCrit, true), v -> ModConfig.colorGradientTopCrit = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Effects"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Fade out"))
                                        .description(OptionDescription.of(Text.literal("Fade the hitbox opacity out as the timer expires.")))
                                        .binding(true, () -> ModConfig.fadeOut, v -> ModConfig.fadeOut = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Pulse"))
                                        .description(OptionDescription.of(Text.literal("Animate hitbox opacity with a pulsing effect.")))
                                        .binding(false, () -> ModConfig.pulse, v -> ModConfig.pulse = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Pulse speed"))
                                        .description(OptionDescription.of(Text.literal("How fast the pulse cycles. 1.0 = once per second.")))
                                        .binding(1.0f, () -> ModConfig.pulseSpeed, v -> ModConfig.pulseSpeed = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.2f, 5.0f).step(0.1f))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Corner-only outline"))
                                        .description(OptionDescription.of(Text.literal("Render only the corner brackets instead of the full outline.")))
                                        .binding(false, () -> ModConfig.cornerOnly, v -> ModConfig.cornerOnly = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Corner length"))
                                        .description(OptionDescription.of(Text.literal("Length of each corner bracket segment in blocks.")))
                                        .binding(0.25f, () -> ModConfig.cornerLength, v -> ModConfig.cornerLength = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.05f, 1.0f).step(0.05f))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Self & Range"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Self-reveal"))
                                        .description(OptionDescription.of(Text.literal("Show your own hitbox.")))
                                        .binding(false, () -> ModConfig.selfReveal, v -> ModConfig.selfReveal = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Self-reveal permanent"))
                                        .description(OptionDescription.of(Text.literal("Show your own hitbox permanently. If off, only shows after you hit someone.")))
                                        .binding(false, () -> ModConfig.selfRevealPermanent, v -> ModConfig.selfRevealPermanent = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Range indicator"))
                                        .description(OptionDescription.of(Text.literal("Show a circle on the ground at your close-range threshold radius.")))
                                        .binding(false, () -> ModConfig.rangeIndicator, v -> ModConfig.rangeIndicator = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Range indicator color"))
                                        .description(OptionDescription.of(Text.literal("Color of the range indicator circle.")))
                                        .binding(new Color(ModConfig.colorRangeIndicator, true), () -> new Color(ModConfig.colorRangeIndicator, true), v -> ModConfig.colorRangeIndicator = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .build())

                        .build())

                // ── Entities ─────────────────────────────────────────────────────
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Entities"))

                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Only enemy projectiles"))
                                .description(OptionDescription.of(Text.literal("Only show hitboxes for projectiles not thrown/shot by you.")))
                                .binding(true, () -> ModConfig.entityOnlyEnemy, v -> ModConfig.entityOnlyEnemy = v)
                                .controller(TickBoxControllerBuilder::create)
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Ender Pearl"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .binding(true, () -> ModConfig.pearlEnabled, v -> ModConfig.pearlEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Color"))
                                        .binding(new Color(ModConfig.colorPearl, true), () -> new Color(ModConfig.colorPearl, true), v -> ModConfig.colorPearl = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Size multiplier"))
                                        .binding(1.0f, () -> ModConfig.pearlSizeMulti, v -> ModConfig.pearlSizeMulti = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 5.0f).step(0.25f).valueFormatter(f -> Text.literal(String.format("%.2fx", f))))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Outline only"))
                                        .binding(false, () -> ModConfig.pearlOutlineOnly, v -> ModConfig.pearlOutlineOnly = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Arrow"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .binding(true, () -> ModConfig.arrowEnabled, v -> ModConfig.arrowEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Color"))
                                        .binding(new Color(ModConfig.colorArrow, true), () -> new Color(ModConfig.colorArrow, true), v -> ModConfig.colorArrow = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Size multiplier"))
                                        .binding(1.0f, () -> ModConfig.arrowSizeMulti, v -> ModConfig.arrowSizeMulti = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 5.0f).step(0.25f).valueFormatter(f -> Text.literal(String.format("%.2fx", f))))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Outline only"))
                                        .binding(false, () -> ModConfig.arrowOutlineOnly, v -> ModConfig.arrowOutlineOnly = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Wind Charge"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .binding(true, () -> ModConfig.windChargeEnabled, v -> ModConfig.windChargeEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Color"))
                                        .binding(new Color(ModConfig.colorWindCharge, true), () -> new Color(ModConfig.colorWindCharge, true), v -> ModConfig.colorWindCharge = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Size multiplier"))
                                        .binding(1.0f, () -> ModConfig.windChargesSizeMulti, v -> ModConfig.windChargesSizeMulti = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 5.0f).step(0.25f).valueFormatter(f -> Text.literal(String.format("%.2fx", f))))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Outline only"))
                                        .binding(false, () -> ModConfig.windChargeOutlineOnly, v -> ModConfig.windChargeOutlineOnly = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("TNT Minecart"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Show hitbox for TNT Minecarts.")))
                                        .binding(true, () -> ModConfig.tntMinecartEnabled, v -> ModConfig.tntMinecartEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Color"))
                                        .binding(new Color(ModConfig.colorTntMinecart, true), () -> new Color(ModConfig.colorTntMinecart, true), v -> ModConfig.colorTntMinecart = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Size multiplier"))
                                        .binding(1.0f, () -> ModConfig.tntMinecartSizeMulti, v -> ModConfig.tntMinecartSizeMulti = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 3.0f).step(0.1f))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Outline only"))
                                        .binding(false, () -> ModConfig.tntMinecartOutlineOnly, v -> ModConfig.tntMinecartOutlineOnly = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Fireball"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Show hitbox for fireballs (ghast, blaze, etc.).")))
                                        .binding(true, () -> ModConfig.fireballEnabled, v -> ModConfig.fireballEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Color"))
                                        .binding(new Color(ModConfig.colorFireball, true), () -> new Color(ModConfig.colorFireball, true), v -> ModConfig.colorFireball = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Size multiplier"))
                                        .binding(1.0f, () -> ModConfig.fireballSizeMulti, v -> ModConfig.fireballSizeMulti = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 3.0f).step(0.1f))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Outline only"))
                                        .binding(false, () -> ModConfig.fireballOutlineOnly, v -> ModConfig.fireballOutlineOnly = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Boat"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Show hitbox for boats and chest boats.")))
                                        .binding(true, () -> ModConfig.boatEnabled, v -> ModConfig.boatEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Color"))
                                        .binding(new Color(ModConfig.colorBoat, true), () -> new Color(ModConfig.colorBoat, true), v -> ModConfig.colorBoat = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Size multiplier"))
                                        .binding(1.0f, () -> ModConfig.boatSizeMulti, v -> ModConfig.boatSizeMulti = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 3.0f).step(0.1f))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Outline only"))
                                        .binding(false, () -> ModConfig.boatOutlineOnly, v -> ModConfig.boatOutlineOnly = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .build())

                // ── Trajectories ─────────────────────────────────────────────────
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Trajectories"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Pearl Trail"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Show a cylindrical trail behind enemy ender pearls.")))
                                        .binding(true, () -> ModConfig.pearlTrailEnabled, v -> ModConfig.pearlTrailEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Trail color (start)"))
                                        .description(OptionDescription.of(Text.literal("Color at the beginning (oldest) end of the trail.")))
                                        .binding(new Color(ModConfig.pearlTrailColorStart, true), () -> new Color(ModConfig.pearlTrailColorStart, true), v -> ModConfig.pearlTrailColorStart = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Trail color (end)"))
                                        .description(OptionDescription.of(Text.literal("Color at the tip (newest) end of the trail.")))
                                        .binding(new Color(ModConfig.pearlTrailColorEnd, true), () -> new Color(ModConfig.pearlTrailColorEnd, true), v -> ModConfig.pearlTrailColorEnd = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Opacity"))
                                        .binding(0.85f, () -> ModConfig.pearlTrailOpacity, v -> ModConfig.pearlTrailOpacity = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 1.0f).step(0.05f))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Width"))
                                        .description(OptionDescription.of(Text.literal("Radius of the trail cylinder. 1.0 = default.")))
                                        .binding(1.0f, () -> ModConfig.pearlTrailWidth, v -> ModConfig.pearlTrailWidth = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.2f, 4.0f).step(0.1f))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Max trail length"))
                                        .description(OptionDescription.of(Text.literal("Maximum number of points stored per pearl trail.")))
                                        .binding(150, () -> ModConfig.pearlTrailMaxPoints, v -> ModConfig.pearlTrailMaxPoints = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(20, 300).step(10))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Trail persist (ms)"))
                                        .description(OptionDescription.of(Text.literal("How long the trail lingers after the pearl lands, in milliseconds.")))
                                        .binding(2000, () -> ModConfig.pearlTrailPersistMs, v -> ModConfig.pearlTrailPersistMs = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(500, 10000).step(500))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Show own pearl trail"))
                                        .description(OptionDescription.of(Text.literal("Also show a trail behind pearls you throw.")))
                                        .binding(false, () -> ModConfig.pearlTrailShowOwn, v -> ModConfig.pearlTrailShowOwn = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Landing Beam"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Show a vertical beam where an enemy pearl lands.")))
                                        .binding(true, () -> ModConfig.pearlLandingBeamEnabled, v -> ModConfig.pearlLandingBeamEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.literal("Beam color"))
                                        .binding(new Color(ModConfig.pearlBeamColor, true), () -> new Color(ModConfig.pearlBeamColor, true), v -> ModConfig.pearlBeamColor = v.getRGB())
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Beam opacity"))
                                        .binding(1.0f, () -> ModConfig.pearlBeamOpacity, v -> ModConfig.pearlBeamOpacity = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 1.0f).step(0.05f))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Beam duration (s)"))
                                        .description(OptionDescription.of(Text.literal("How many seconds the beam stays visible.")))
                                        .binding(3.0f, () -> ModConfig.pearlBeamDuration, v -> ModConfig.pearlBeamDuration = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 10.0f).step(0.5f))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Landing particles"))
                                        .description(OptionDescription.of(Text.literal("Spawn portal particles when a pearl lands.")))
                                        .binding(true, () -> ModConfig.pearlLandingParticles, v -> ModConfig.pearlLandingParticles = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Lightning effect"))
                                        .description(OptionDescription.of(Text.literal("Show an animated lightning bolt at the landing beam.")))
                                        .binding(true, () -> ModConfig.pearlLightningEnabled, v -> ModConfig.pearlLightningEnabled = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .build())

                // ── Friends ──────────────────────────────────────────────────────
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Friends"))
                        .group(ListOption.<String>createBuilder()
                                .name(Text.literal("Friends (Ignore List)"))
                                .description(OptionDescription.of(Text.literal("Players in this list will never have their hitbox revealed.")))
                                .binding(new java.util.ArrayList<>(), () -> ModConfig.friends, v -> ModConfig.friends = new java.util.ArrayList<>(v))
                                .controller(StringControllerBuilder::create)
                                .initial("")
                                .insertEntriesAtEnd(true)
                                .build())
                        .build())

                .build()
                .generateScreen(parent);
    }
}